# Task 1

## Creating NumpyArrays

In [4]:
import numpy as np
arr1 = np.arange(1, 10)
arr2 =np.arange(1,10).reshape(3,3)
arr3 = np.array([10,20,30,40,50])

print("array 1:\n",arr1, "\nshape:", arr1.shape , "datatype:", arr1.dtype)
print("array 2:\n",arr2, "\nshape:", arr2.shape , "datatype:", arr2.dtype)
print("array 3:\n",arr3, "\nshape:", arr3.shape , "datatype:", arr3.dtype)

array 1:
 [1 2 3 4 5 6 7 8 9] 
shape: (9,) datatype: int64
array 2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
shape: (3, 3) datatype: int64
array 3:
 [10 20 30 40 50] 
shape: (5,) datatype: int64


## Task 2

## Important mathematical Operations

In [6]:
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])
print("Addition:", A + B)
print("Subtraction:", A - B)    
print("Multiplication:", A * B)
print("Division:", A / B)
print("Power:", A ** 2)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Power: [ 100  400  900 1600]


## Task 3

## Important Numpy Mathematical Formulas

In [8]:
values  = np.array([2,4,6,8,10])
print("Square root:", np.sqrt(values))
print("Exponential:", np.exp(values))
print("Logarithm:", np.log(values))
print("sum of all elements:", np.sum(values))
print("Cumulative sum of elements:", np.cumsum(values))

Square root: [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Exponential: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
Logarithm: [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
sum of all elements: 30
Cumulative sum of elements: [ 2  6 12 20 30]


# Task 4

## Aggregation Operations

In [17]:
data = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Row wise sum:", np.sum(data, axis=1))
print("Column wise sum:", np.sum(data, axis=0))
print("Minimum value:", np.min(data))
print("Maximum value:", np.max(data))
print("Mean value:", np.mean(data))
print("Minimum value along rows:", np.min(data, axis=1))
print("Maximum value along rows:", np.max(data, axis=1))
print("Max value along columns:", np.max(data, axis=0))
print("Minimum value along columns:", np.min(data, axis=0))

Row wise sum: [ 60 150 240]
Column wise sum: [120 150 180]
Minimum value: 10
Maximum value: 90
Mean value: 50.0
Minimum value along rows: [10 40 70]
Maximum value along rows: [30 60 90]
Max value along columns: [70 80 90]
Minimum value along columns: [10 20 30]


# Task 5

## Statistical Operations (Core Focus)

In [18]:
marks = np.array([78,85,90,66,72,88,95,60])
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Variance:", np.var(marks))
print("Standard Deviation:", np.std(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))  
print("range:" , np.max(marks) - np.min(marks))  

Mean: 79.25
Median: 81.5
Variance: 134.1875
Standard Deviation: 11.583932838203095
Minimum: 60
Maximum: 95
range: 35


# Task 6

## Percentile & Sorting

In [19]:
marks = np.array([78,85,90,66,72,88,95,60])
print("Sorted marks:", np.sort(marks))
## Find 25th percentile
print("25th percentile:", np.percentile(marks, 25))
## Find 50th percentile (median)
print("50th percentile (median):", np.percentile(marks, 50))
## Find 75th percentile
print("75th percentile:", np.percentile(marks, 75))
## Count how many student  score are above avarage
average_score = np.mean(marks)
above_average_count = np.sum(marks > average_score)
print("Number of students scoring above average:", above_average_count)


Sorted marks: [60 66 72 78 85 88 90 95]
25th percentile: 70.5
50th percentile (median): 81.5
75th percentile: 88.5
Number of students scoring above average: 4


# Task 7

## Mini Use Cse Sales Analysis:

In [20]:
sales = np.array([1200, 1500,900 ,2000,1800, 1700, 1600])
# Total weekly sales
total_sales = np.sum(sales)
print("Total weekly sales:", total_sales)
# Average daily sales
average_sales = np.mean(sales)
print("Average daily sales:", average_sales)
#Highest and lowest sales day
highest_sales = np.max(sales)
lowest_sales = np.min(sales)
print("Highest sales in a day:", highest_sales)
print("Lowest sales in a day:", lowest_sales)
# Standard deviation of sales
sales_std_dev = np.std(sales)
print("Standard deviation of sales:", sales_std_dev)
## Indentify the sales where sales are above average
above_average_sales = sales[sales > average_sales]
print("Sales above average:", above_average_sales)

Total weekly sales: 10700
Average daily sales: 1528.5714285714287
Highest sales in a day: 2000
Lowest sales in a day: 900
Standard deviation of sales: 345.2298849598449
Sales above average: [2000 1800 1700 1600]
